# Generated by Django 4.2.5 on 2023-10-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year_of_issue', models.PositiveSmallIntegerField()),
                ('short_description', models.TextField()),
                ('rating', models.SmallIntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')], max_length=1)),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Triller', 'Thriller'), ('Drama', 'Drama')], max_length=20)),
                ('cover', models.ImageField(upload_to='covers')),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
