# Generated by Django 4.2.5 on 2023-10-08 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_film_short_description_film_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(
                null=True, 
                blank=True, 
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]
                ),
        ),
    ]
